use std::fmt::Display;

use crate::{
    background::{BackgroundBaseState, PreBackgroundBase},
    PreBaseState, PreStyleBase, StyleBaseState,
};

use super::Style;

#[derive(Hash, Eq, PartialEq)]
#[allow(non_camel_case_types)]
pub enum Color {
    Hex(u32),
    THex(u32),
    Rgb(u8, u8, u8),
    Rgba(u8, u8, u8, u8),
    Hsl(u16, u8, u8),
    Hsla(u16, u8, u8, u8),
    ALICEBLUE,
    ANTIQUEWHITE,
    AQUA,
    AQUAMARINE,
    AZURE,
    BEIGE,
    BISQUE,
    BLACK,
    BLANCHEDALMOND,
    BLUE,
    BLUEVIOLET,
    BROWN,
    BURLYWOOD,
    CADETBLUE,
    CHARTREUSE,
    CHOCOLATE,
    CORAL,
    CORNFLOWERBLUE,
    CORNSILK,
    CRIMSON,
    CYAN,
    DARKBLUE,
    DARKCYAN,
    DARKGOLDENROD,
    DARKGREY,
    DARKGREEN,
    DARKKHAKI,
    DARKMAGENTA,
    DARKOLIVEGREEN,
    DARKORANGE,
    DARKORCHID,
    DARKRED,
    DARKSALMON,
    DARKSEAGREEN,
    DARKSLATEBLUE,
    DARKSLATEGREY,
    DARKTURQUOISE,
    DARKVIOLET,
    DEEPPINK,
    DEEPSKYBLUE,
    DIMGRAY,
    DODGERBLUE,
    FIREBRICK,
    FLORALWHITE,
    FORESTGREEN,
    FUCHSIA,
    GAINSBORO,
    GHOSTWHITE,
    GOLD,
    GOLDENROD,
    GREY,
    GREEN,
    GREENYELLOW,
    HONEYDEW,
    HOTPINK,
    INDIANRED,
    INDIGO,
    IVORY,
    KHAKI,
    LAVENDER,
    LAVENDERBLUSH,
    LAWNGREEN,
    LEMONCHIFFON,
    LIGHTBLUE,
    LIGHTCORAL,
    LIGHTCYAN,
    LIGHTGOLDENRODYELLOW,
    LIGHTGREY,
    LIGHTGREEN,
    LIGHTPINK,
    LIGHTSALMON,
    LIGHTSEAGREEN,
    LIGHTSKYBLUE,
    LIGHTSLATEGREY,
    LIGHTSTEELBLUE,
    LIGHTYELLOW,
    LIME,
    LIMEGREEN,
    LINEN,
    MAGENTA,
    MAROON,
    MEDIUMAQUAMARINE,
    MEDIUMBLUE,
    MEDIUMORCHID,
    MEDIUMPURPLE,
    MEDIUMSEAGREEN,
    MEDIUMSLATEBLUE,
    MEDIUMSPRINGGREEN,
    MEDIUMTURQUOISE,
    MEDIUMVIOLETRED,
    MIDNIGHTBLUE,
    MINTCREAM,
    MISTYROSE,
    MOCCASIN,
    NAVAJOWHITE,
    NAVY,
    OLDLACE,
    OLIVE,
    OLIVEDRAB,
    ORANGE,
    ORANGERED,
    ORCHID,
    PALEGOLDENROD,
    PALEGREEN,
    PALETURQUOISE,
    PALEVIOLETRED,
    PAPAYAWHIP,
    PEACHPUFF,
    PERU,
    PINK,
    PLUM,
    POWDERBLUE,
    PURPLE,
    RED,
    ROSYBROWN,
    ROYALBLUE,
    SADDLEBROWN,
    SALMON,
    SANDYBROWN,
    SEAGREEN,
    SEASHELL,
    SIENNA,
    SILVER,
    SKYBLUE,
    SLATEBLUE,
    SLATEGREY,
    SNOW,
    SPRINGGREEN,
    STEELBLUE,
    TAN,
    TEAL,
    THISTLE,
    TOMATO,
    TURQUOISE,
    VIOLET,
    WHEAT,
    WHITE,
    WHITESMOKE,
    YELLOW,
    YELLOWGREEN,
}

use paste::paste;

macro_rules! one_color {
    ($output:ident,$($name:ident),+) => {
        $(
            paste! {
                pub fn $name(self) -> Style<$output> {
                    self.base(Color::[<$name:upper>])
                }
            }
        )*
    };
}

macro_rules! color_impl {
    ($target:ident,$output:ident) => {
        impl Style<$target<Color>> {
            pub fn hex(self, hex: u32) -> Style<$output> {
                self.base(Color::Hex(hex))
            }

            pub fn t_hex(self, hex: u32) -> Style<$output> {
                self.base(Color::THex(hex))
            }

            pub fn rgb(self, red: u8, green: u8, blue: u8) -> Style<$output> {
                self.base(Color::Rgb(red, green, blue))
            }

            pub fn rgba(self, red: u8, green: u8, blue: u8, opacity: u8) -> Style<$output> {
                debug_assert!(opacity <= 100, "opacity is from 0 to 100 not from 0 to 1");
                self.base(Color::Rgba(red, green, blue, opacity))
            }

            pub fn hsl(self, hue: u16, saturation: u8, lightness: u8) -> Style<$output> {
                debug_assert!(hue <= 360, "hue should be from 0 to 360");
                debug_assert!(saturation <= 100, "saturation should be from 0 to 100");
                debug_assert!(lightness <= 100, "lightness should be from 0 to 100");
                self.base(Color::Hsl(hue, saturation, lightness))
            }

            pub fn hsla(
                self,
                hue: u16,
                saturation: u8,
                lightness: u8,
                opacity: u8,
            ) -> Style<$output> {
                debug_assert!(hue <= 360, "hue should be from 0 to 360");
                debug_assert!(saturation <= 100, "saturation should be from 0 to 100");
                debug_assert!(lightness <= 100, "lightness should be from 0 to 100");
                debug_assert!(opacity <= 100, "opacity is from 0 to 100 not from 0 to 1");
                self.base(Color::Hsla(hue, saturation, lightness, opacity))
            }

            one_color!(
                $output,
                aliceblue,
                antiquewhite,
                aqua,
                aquamarine,
                azure,
                beige,
                bisque,
                black,
                blanchedalmond,
                blue,
                blueviolet,
                brown,
                burlywood,
                cadetblue,
                chartreuse,
                chocolate,
                coral,
                cornflowerblue,
                cornsilk,
                crimson,
                cyan,
                darkblue,
                darkcyan,
                darkgoldenrod,
                darkgrey,
                darkgreen,
                darkkhaki,
                darkmagenta,
                darkolivegreen,
                darkorange,
                darkorchid,
                darkred,
                darksalmon,
                darkseagreen,
                darkslateblue,
                darkslategrey,
                darkturquoise,
                darkviolet,
                deeppink,
                deepskyblue,
                dimgray,
                dodgerblue,
                firebrick,
                floralwhite,
                forestgreen,
                fuchsia,
                gainsboro,
                ghostwhite,
                gold,
                goldenrod,
                grey,
                green,
                greenyellow,
                honeydew,
                hotpink,
                indianred,
                indigo,
                ivory,
                khaki,
                lavender,
                lavenderblush,
                lawngreen,
                lemonchiffon,
                lightblue,
                lightcoral,
                lightcyan,
                lightgoldenrodyellow,
                lightgrey,
                lightgreen,
                lightpink,
                lightsalmon,
                lightseagreen,
                lightskyblue,
                lightslategrey,
                lightsteelblue,
                lightyellow,
                lime,
                limegreen,
                linen,
                magenta,
                maroon,
                mediumaquamarine,
                mediumblue,
                mediumorchid,
                mediumpurple,
                mediumseagreen,
                mediumslateblue,
                mediumspringgreen,
                mediumturquoise,
                mediumvioletred,
                midnightblue,
                mintcream,
                mistyrose,
                moccasin,
                navajowhite,
                navy,
                oldlace,
                olive,
                olivedrab,
                orange,
                orangered,
                orchid,
                palegoldenrod,
                palegreen,
                paleturquoise,
                palevioletred,
                papayawhip,
                peachpuff,
                peru,
                pink,
                plum,
                powderblue,
                purple,
                red,
                rosybrown,
                royalblue,
                saddlebrown,
                salmon,
                sandybrown,
                seagreen,
                seashell,
                sienna,
                silver,
                skyblue,
                slateblue,
                slategrey,
                snow,
                springgreen,
                steelblue,
                tan,
                teal,
                thistle,
                tomato,
                turquoise,
                violet,
                wheat,
                white,
                whitesmoke,
                yellow,
                yellowgreen
            );
        }
    };
}

color_impl!(PreBackgroundBase, BackgroundBaseState);
color_impl!(PreStyleBase, StyleBaseState);

impl Display for Color {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let result = match self {
            Color::Hex(c) => {
                let result = format!("{c:#06x}")[2..].to_string();
                format!("#{result}")
            }
            Color::THex(c) => {
                let result = format!("{c:#08x}")[2..].to_string();
                format!("#{result}")
            }
            Color::Rgb(red, green, blue) => format!("rgb({red},{green},{blue})"),
            Color::Rgba(red, green, blue, opacity) => {
                format!("rgba({red},{green},{blue},{})", *opacity as f32 / 100.)
            }
            Color::Hsl(hue, saturation, lightness) => {
                format!("hsl({hue},{saturation}%,{lightness}%)")
            }
            Color::Hsla(hue, saturation, lightness, opacity) => {
                format!(
                    "hsl({hue},{saturation}%,{lightness}%,{})",
                    *opacity as f32 / 100.
                )
            }
            Color::ALICEBLUE => "aliceblue".to_string(),
            Color::ANTIQUEWHITE => "antiquewhite".to_string(),
            Color::AQUA => "aqua".to_string(),
            Color::AQUAMARINE => "aquamarine".to_string(),
            Color::AZURE => "azure".to_string(),
            Color::BEIGE => "beige".to_string(),
            Color::BISQUE => "bisque".to_string(),
            Color::BLACK => "black".to_string(),
            Color::BLANCHEDALMOND => "blanchedalmond".to_string(),
            Color::BLUE => "blue".to_string(),
            Color::BLUEVIOLET => "blueviolet".to_string(),
            Color::BROWN => "brown".to_string(),
            Color::BURLYWOOD => "burlywood".to_string(),
            Color::CADETBLUE => "cadetblue".to_string(),
            Color::CHARTREUSE => "chartreuse".to_string(),
            Color::CHOCOLATE => "chocolate".to_string(),
            Color::CORAL => "coral".to_string(),
            Color::CORNFLOWERBLUE => "cornflowerblue".to_string(),
            Color::CORNSILK => "cornsilk".to_string(),
            Color::CRIMSON => "crimson".to_string(),
            Color::CYAN => "cyan".to_string(),
            Color::DARKBLUE => "darkblue".to_string(),
            Color::DARKCYAN => "darkcyan".to_string(),
            Color::DARKGOLDENROD => "darkgoldenrod".to_string(),
            Color::DARKGREY => "darkgrey".to_string(),
            Color::DARKGREEN => "darkgreen".to_string(),
            Color::DARKKHAKI => "darkkhaki".to_string(),
            Color::DARKMAGENTA => "darkmagenta".to_string(),
            Color::DARKOLIVEGREEN => "darkolivegreen".to_string(),
            Color::DARKORANGE => "darkorange".to_string(),
            Color::DARKORCHID => "darkorchid".to_string(),
            Color::DARKRED => "darkred".to_string(),
            Color::DARKSALMON => "darksalmon".to_string(),
            Color::DARKSEAGREEN => "darkseagreen".to_string(),
            Color::DARKSLATEBLUE => "darkslateblue".to_string(),
            Color::DARKSLATEGREY => "darkslategrey".to_string(),
            Color::DARKTURQUOISE => "darkturquoise".to_string(),
            Color::DARKVIOLET => "darkviolet".to_string(),
            Color::DEEPPINK => "deeppink".to_string(),
            Color::DEEPSKYBLUE => "deepskyblue".to_string(),
            Color::DIMGRAY => "dimgray".to_string(),
            Color::DODGERBLUE => "dodgerblue".to_string(),
            Color::FIREBRICK => "firebrick".to_string(),
            Color::FLORALWHITE => "floralwhite".to_string(),
            Color::FORESTGREEN => "forestgreen".to_string(),
            Color::FUCHSIA => "fuchsia".to_string(),
            Color::GAINSBORO => "gainsboro".to_string(),
            Color::GHOSTWHITE => "ghostwhite".to_string(),
            Color::GOLD => "gold".to_string(),
            Color::GOLDENROD => "goldenrod".to_string(),
            Color::GREY => "grey".to_string(),
            Color::GREEN => "green".to_string(),
            Color::GREENYELLOW => "greenyellow".to_string(),
            Color::HONEYDEW => "honeydew".to_string(),
            Color::HOTPINK => "hotpink".to_string(),
            Color::INDIANRED => "indianred".to_string(),
            Color::INDIGO => "indigo".to_string(),
            Color::IVORY => "ivory".to_string(),
            Color::KHAKI => "khaki".to_string(),
            Color::LAVENDER => "lavender".to_string(),
            Color::LAVENDERBLUSH => "lavenderblush".to_string(),
            Color::LAWNGREEN => "lawngreen".to_string(),
            Color::LEMONCHIFFON => "lemonchiffon".to_string(),
            Color::LIGHTBLUE => "lightblue".to_string(),
            Color::LIGHTCORAL => "lightcoral".to_string(),
            Color::LIGHTCYAN => "lightcyan".to_string(),
            Color::LIGHTGOLDENRODYELLOW => "lightgoldenrodyellow".to_string(),
            Color::LIGHTGREY => "lightgrey".to_string(),
            Color::LIGHTGREEN => "lightgreen".to_string(),
            Color::LIGHTPINK => "lightpink".to_string(),
            Color::LIGHTSALMON => "lightsalmon".to_string(),
            Color::LIGHTSEAGREEN => "lightseagreen".to_string(),
            Color::LIGHTSKYBLUE => "lightskyblue".to_string(),
            Color::LIGHTSLATEGREY => "lightslategrey".to_string(),
            Color::LIGHTSTEELBLUE => "lightsteelblue".to_string(),
            Color::LIGHTYELLOW => "lightyellow".to_string(),
            Color::LIME => "lime".to_string(),
            Color::LIMEGREEN => "limegreen".to_string(),
            Color::LINEN => "linen".to_string(),
            Color::MAGENTA => "magenta".to_string(),
            Color::MAROON => "maroon".to_string(),
            Color::MEDIUMAQUAMARINE => "mediumaquamarine".to_string(),
            Color::MEDIUMBLUE => "mediumblue".to_string(),
            Color::MEDIUMORCHID => "mediumorchid".to_string(),
            Color::MEDIUMPURPLE => "mediumpurple".to_string(),
            Color::MEDIUMSEAGREEN => "mediumseagreen".to_string(),
            Color::MEDIUMSLATEBLUE => "mediumslateblue".to_string(),
            Color::MEDIUMSPRINGGREEN => "mediumspringgreen".to_string(),
            Color::MEDIUMTURQUOISE => "mediumturquoise".to_string(),
            Color::MEDIUMVIOLETRED => "mediumvioletred".to_string(),
            Color::MIDNIGHTBLUE => "midnightblue".to_string(),
            Color::MINTCREAM => "mintcream".to_string(),
            Color::MISTYROSE => "mistyrose".to_string(),
            Color::MOCCASIN => "moccasin".to_string(),
            Color::NAVAJOWHITE => "navajowhite".to_string(),
            Color::NAVY => "navy".to_string(),
            Color::OLDLACE => "oldlace".to_string(),
            Color::OLIVE => "olive".to_string(),
            Color::OLIVEDRAB => "olivedrab".to_string(),
            Color::ORANGE => "orange".to_string(),
            Color::ORANGERED => "orangered".to_string(),
            Color::ORCHID => "orchid".to_string(),
            Color::PALEGOLDENROD => "palegoldenrod".to_string(),
            Color::PALEGREEN => "palegreen".to_string(),
            Color::PALETURQUOISE => "paleturquoise".to_string(),
            Color::PALEVIOLETRED => "palevioletred".to_string(),
            Color::PAPAYAWHIP => "papayawhip".to_string(),
            Color::PEACHPUFF => "peachpuff".to_string(),
            Color::PERU => "peru".to_string(),
            Color::PINK => "pink".to_string(),
            Color::PLUM => "plum".to_string(),
            Color::POWDERBLUE => "powderblue".to_string(),
            Color::PURPLE => "purple".to_string(),
            Color::RED => "red".to_string(),
            Color::ROSYBROWN => "rosybrown".to_string(),
            Color::ROYALBLUE => "royalblue".to_string(),
            Color::SADDLEBROWN => "saddlebrown".to_string(),
            Color::SALMON => "salmon".to_string(),
            Color::SANDYBROWN => "sandybrown".to_string(),
            Color::SEAGREEN => "seagreen".to_string(),
            Color::SEASHELL => "seashell".to_string(),
            Color::SIENNA => "sienna".to_string(),
            Color::SILVER => "silver".to_string(),
            Color::SKYBLUE => "skyblue".to_string(),
            Color::SLATEBLUE => "slateblue".to_string(),
            Color::SLATEGREY => "slategrey".to_string(),
            Color::SNOW => "snow".to_string(),
            Color::SPRINGGREEN => "springgreen".to_string(),
            Color::STEELBLUE => "steelblue".to_string(),
            Color::TAN => "tan".to_string(),
            Color::TEAL => "teal".to_string(),
            Color::THISTLE => "thistle".to_string(),
            Color::TOMATO => "tomato".to_string(),
            Color::TURQUOISE => "turquoise".to_string(),
            Color::VIOLET => "violet".to_string(),
            Color::WHEAT => "wheat".to_string(),
            Color::WHITE => "white".to_string(),
            Color::WHITESMOKE => "whitesmoke".to_string(),
            Color::YELLOW => "yellow".to_string(),
            Color::YELLOWGREEN => "yellowgreen".to_string(),
        };
        write!(f, "{}", result)
    }
}
