default_theme = "dracula"
default_font_size = "small"
theme_notification = true
live_config_reload = true

[keys]
increase_fontsize = "equal"
decrease_fontsize = "minus"
help = "slash"

[keys.print]
letter = "p"

[keys.next_theme]
letter = "j"

[keys.prev_theme]
letter = "k"

[keys.next_slide]
letter = "l"

[keys.prev_slide]
letter = "h"
